# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 446)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabChanger = SegmentedWidget(Form)
        self.tabChanger.setObjectName("tabChanger")
        self.verticalLayout_3.addWidget(self.tabChanger)
        self.tabs = SlidingStackedWidget(Form)
        self.tabs.setObjectName("tabs")
        self.userApps = QtWidgets.QWidget()
        self.userApps.setObjectName("userApps")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.userApps)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SmoothScrollArea_2 = SmoothScrollArea(self.userApps)
        self.SmoothScrollArea_2.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.SmoothScrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SmoothScrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SmoothScrollArea_2.setWidgetResizable(True)
        self.SmoothScrollArea_2.setObjectName("SmoothScrollArea_2")
        self.userApps_widget = QtWidgets.QWidget(self.SmoothScrollArea_2)
        self.userApps_widget.setGeometry(QtCore.QRect(0, 0, 755, 350))
        self.userApps_widget.setObjectName("userApps_widget")
        self.verticalLayout.addWidget(self.SmoothScrollArea_2)
        self.tabs.addWidget(self.userApps)
        self.systemApps = QtWidgets.QWidget()
        self.systemApps.setObjectName("systemApps")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.systemApps)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SmoothScrollArea = SmoothScrollArea(self.systemApps)
        self.SmoothScrollArea.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.SmoothScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SmoothScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.systemApps_widget = QtWidgets.QWidget(self.SmoothScrollArea)
        self.systemApps_widget.setGeometry(QtCore.QRect(0, 0, 257, 210))
        self.systemApps_widget.setObjectName("systemApps_widget")
        self.verticalLayout_2.addWidget(self.SmoothScrollArea)
        self.tabs.addWidget(self.systemApps)
        self.verticalLayout_3.addWidget(self.tabs)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.scan_apps = PushButton(Form)
        self.scan_apps.setObjectName("scan_apps")
        self.verticalLayout_4.addWidget(self.scan_apps)

        self.retranslateUi(Form)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.scan_apps.setText(_translate("Form", "扫描应用"))
from cmosui import SlidingStackedWidget
from qfluentwidgets import PushButton, SegmentedWidget, SmoothScrollArea
