# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 446)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 110, 276, 249))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabChanger = SegmentedWidget(self.layoutWidget)
        self.tabChanger.setObjectName("tabChanger")
        self.verticalLayout_3.addWidget(self.tabChanger)
        self.tabs = SlidingStackedWidget(self.layoutWidget)
        self.tabs.setObjectName("tabs")
        self.userApps = QtWidgets.QWidget()
        self.userApps.setObjectName("userApps")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.userApps)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ListWidget = ListWidget(self.userApps)
        self.ListWidget.setObjectName("ListWidget")
        self.verticalLayout.addWidget(self.ListWidget)
        self.HyperlinkLabel = HyperlinkLabel(self.userApps)
        self.HyperlinkLabel.setObjectName("HyperlinkLabel")
        self.verticalLayout.addWidget(self.HyperlinkLabel)
        self.StrongBodyLabel = StrongBodyLabel(self.userApps)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout.addWidget(self.StrongBodyLabel)
        self.tabs.addWidget(self.userApps)
        self.systemApps = QtWidgets.QWidget()
        self.systemApps.setObjectName("systemApps")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.systemApps)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ListWidget_2 = ListWidget(self.systemApps)
        self.ListWidget_2.setObjectName("ListWidget_2")
        self.verticalLayout_2.addWidget(self.ListWidget_2)
        self.label = QtWidgets.QLabel(self.systemApps)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tabs.addWidget(self.systemApps)
        self.verticalLayout_3.addWidget(self.tabs)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(30, 110, 256, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)

        self.retranslateUi(Form)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.HyperlinkLabel.setText(_translate("Form", "Hyperlink label"))
        self.StrongBodyLabel.setText(_translate("Form", "Strong body label"))
        self.label.setText(_translate("Form", "TextLabel"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "新建项目"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "新建项目"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "新建项目"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "新建项目"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "新建项目"))
        item = self.listWidget.item(5)
        item.setText(_translate("Form", "新建项目"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
from cmosui import SlidingStackedWidget
from qfluentwidgets import HyperlinkLabel, ListWidget, SegmentedWidget, StrongBodyLabel
